//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        public int id { get; set; }
        public Nullable<int> persona_id { get; set; }
        public Nullable<int> city_id { get; set; }
        public string direccion1 { get; set; }
    
        public virtual city city { get; set; }
        public virtual persona persona { get; set; }
    }
}
