//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecoffeeEntities : DbContext
    {
        public RecoffeeEntities()
            : base("name=RecoffeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<admin_finca> admin_finca { get; set; }
        public virtual DbSet<carrito> carrito { get; set; }
        public virtual DbSet<carrito_producto> carrito_producto { get; set; }
        public virtual DbSet<categoria_producto> categoria_producto { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<departament> departament { get; set; }
        public virtual DbSet<direccion> direccion { get; set; }
        public virtual DbSet<finca> finca { get; set; }
        public virtual DbSet<module> module { get; set; }
        public virtual DbSet<module_role> module_role { get; set; }
        public virtual DbSet<module_view> module_view { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<recoleccion> recoleccion { get; set; }
        public virtual DbSet<recolector> recolector { get; set; }
        public virtual DbSet<recolectores_finca> recolectores_finca { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<servicio_recolector> servicio_recolector { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<vista> vista { get; set; }
    }
}
