//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class module_view
    {
        public int id { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<int> view_id { get; set; }
    
        public virtual module module { get; set; }
        public virtual vista vista { get; set; }
    }
}
